### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by Magic-123** [jannctu/Rcf-Pytorch-Wrapper#1]
请问一下,我准备了很多图片来测试这个模型,可是当图片测试到第4张的时候,就报错(GPU存储空间挺大的),出现错误:

RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1525812548180/work/aten/src/THC/generic/THCStorage.cu:58
请问作者遇到了吗?如果遇到了,是如何解决的啊?谢谢

**Comment by jannctu** [comment]
hi @Magic-123 

How many testing sets do you have? 
I think if you did not change my code, it won't be out of memory. because I set batch size = 1. 
You may use smaller batch size. 

Thank you 
Jan

**Comment by Magic-123** [comment]
Thank you. I solved the problem by turning down the batch size
